version: "3"
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - DB_URI=mongodb://mongo:27017/game
      - JWT_SECRET=yourSecret
  mongo:
    image: mongo
    ports:
      - "27017:27017"
